---
name: XGTHelpOP
version: 0.0.1
main: XGDAVIDYT\XGTHelpOP\Main
api: 3.12.0
author: XGDAVIDYT
commands:
  helpop: 
    description: Ask for help being OP.
  checkop:
    description: Check ops online.
...
