---
name: XGTHelpOP
version: 1.0.0
main: XGDAVIDYT\XGTHelpOP\Main
api: 3.14.1
author: XGDAVIDYT
commands:
  helpop: 
    description: Ask for help being OP.
  checkop:
    description: Check ops online.
...
